config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#one"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P1Cero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="navbar-inverse"> 
      <!-- Links --> 
      <ul class="navbar-nav"> 
        <li class="nav-item"><%= link_to "one", pages_one_path %></li> 
        <li class="nav-item"><%= link_to "two", pages_two_path %></li> 
        <li class="nav-item"><%= link_to "three", pages_three_path %></li> 
      </ul> 
    </nav> 


    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Claudio Zeiss Martinez</h1>
<p>Find me in app/views/pages/one.html.erb</p>

app/views/pages/three.html.erb
<h2>"Holas como estas"</h2>
<p>
    loremIpsus primer parrafo qweweeeqqedfsc  scscscscsccs
</p>

app/views/pages/two.html.erb
<h1>"Imagen de Pantralla "</h1>
<!--<p>Find me in app/views/pages/two.html.erb</p>-->
<%= image_tag "Imagen_routes.png" %>